version: '3.8'

services:
  prompt-manager:
    container_name: prompt-manager
    build: .
    ports:
      - "45000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
    env_file:
      - .env
    restart: unless-stopped
